
;  ==== 编译环境 ====
[env:red_bank_s3]
extends = esp32s3_base                              ; 继承名为 esp32s3_base 的 父环境配置
board = red_bank_s3                                 ; 是否为自定义板型（需在 boards/ 目录提供 JSON 定义文件）
board_check = true                                  ; 编译前会检查 board 字段是否有效，若无效则报错

; ==== 调试配置 ====
debug_tool = esp-builtin                            ; 使用内置USB-JTAG
; debug_port = COM4                                 ; 指定端口号 自动选择

; ==== 下载配置 ====
upload_protocol = esp-builtin                       ; 使用内置USB-JTAG

; ==== 串口监视配置 ====
; monitor_port = COM4                               ; 指定端口号 自动选择
monitor_speed = 115200                              ; 指定波特率
monitor_filters = esp32_exception_decoder           ; 当 ESP32 运行时发生崩溃（如内存错误、断言失败、看门狗触发等），会输出 十六进制格式的异常调用栈

; ==== 编译配置 ====
build_type = debug                                  ; 配置构建模式的关键参数 debug / release 模式
build_flags =                                       ; 向底层编译器传递额外的 编译选项 和 宏定义
    -DRED_BANK_S3                                   ; 定义宏 RED_BANK_S3
    ${esp32s3_base.build_flags}                     ; 继承预先定义的 esp32s3_base 配置中的基础编译标志
    ; ==== 调试 ====
    -Og                                             ; 启用调试符号，不可以拆开 O g
    -ggdb3                                          ; 生成GDB调试信息，不可以拆开 g gdb3
    -DARDUINO_USB_MODE=1                            ; 启用USB模式
    -DARDUINO_USB_CDC_ON_BOOT=1                     ; 启动时自动初始化 USB CDC
    ; ==== 墨水屏 ====
    -DUSE_EINK
    -DEINK_DISPLAY_MODEL=GxEPD2_270
    -DEINK_WIDTH=264
    -DEINK_HEIGHT=176
    -DUSE_EINK_DYNAMICDISPLAY                       ; Enable Dynamic EInk
    -DEINK_LIMIT_FASTREFRESH=10                     ; How many consecutive fast-refreshes are permitted
    ; ==== 硬件接口 ====
    ; -DMESHTASTIC_MINIMIZE_BUILD=1                 ; 最小化编译体积，移除不必要的库和功能
    ; -DMESHTASTIC_EXCLUDE_MODULES=1                ; 排除 Meshtastic 模块，减少编译体积
    -DPRIVATE_HW                                    ; 标记该项目使用 私有硬件设计（非标准开发板）代码中通过 #ifdef PRIVATE_HW 区分公开硬件和定制硬件的逻辑
    -Ivariants/red_bank_s3                          ; 添加头文件搜索路径，指向自定义硬件配置目录 variants/red_bank_s3

; ==== 依赖库配置 ====
lib_deps =
    ${esp32s3_base.lib_deps}                        ; 继承 esp32s3_base 配置中定义的基础库依赖（如 WiFi、BLE、Arduino 核心库等）
    https://github.com/meshtastic/GxEPD2/archive/b202ebfec6a4821e098cf7a625ba0f6f2400292d.zip ; 不知道为什么没有生效 zinggjm/GxEPD2@^1.3.4, 先改后删也不行，算了
